apiVersion: v1
kind: Pod
metadata:
  name: nginx-sec
  namespace: web
  labels:
    role: webserv
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80

--- 

apiVersion: v1
kind: Pod
metadata:
  name: nginx-sec2
  namespace: web2
  labels:
    role: webserv2
    app: gelatine
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-sec3
  namespace: web2
  labels:
    role: webserv3
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
